# Automatically generated by configure - do not modify
TARGET_RISCV64=y
TARGET_NAME=riscv64
TARGET_BASE_ARCH=riscv
TARGET_ABI_DIR=riscv
CONFIG_SOFTMMU=y
TARGET_SUPPORTS_MTTCG=y
TARGET_XML_FILES= /workspaces/cs179f-winter25-axie006/qemu-4.1.1/gdb-xml/riscv-64bit-cpu.xml /workspaces/cs179f-winter25-axie006/qemu-4.1.1/gdb-xml/riscv-64bit-fpu.xml /workspaces/cs179f-winter25-axie006/qemu-4.1.1/gdb-xml/riscv-64bit-csr.xml
CONFIG_I386_DIS=y
CONFIG_RISCV_DIS=y
LDFLAGS+=
QEMU_CFLAGS+=
